[package]
name = "cargo-dep-viewer"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = {version = "^0.29", features = ["serde"]}
tui-textarea = "^0.7"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
anyhow = "1.0.98"
clap = { version = "4.4", features = ["derive"] }
thiserror = "^2.0"
[env]
RUST_BACKTRACE = "1"